### ISSUE TITLE
undefined method `for_function' for []:Array

### ISSUE THREAD

**Issue by joren** [spanner/radiant-reader_group-extension#6]
I get this error when 

``` @group.messages.for_function('invitation').first```
is called. So I can't create new people or active a new account.

Is their another extension or gem that is required beside the radiant-reader-extension?
```

**Comment by spanner** [comment]
No, you should have everything there. I think it's a migration issue, and probably something I've mangled in recent updates. The underlying problem is that the group has no messages (and that I'm not catching the error properly). I fix. Sorry!
